version: '2'
services:
  front:
    build: ./front
    ports:
      - '80:80'
    depends_on:
      - back
  back:
    build: ./back
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'